services:
  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - DATABASE_URL=file:/data/sqlite.db
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - USE_BREVO=false
      - BREVO_EMAIL=${BREVO_EMAIL}
      - BREVO_SMTP_KEY=${BREVO_SMTP_KEY}
      - BREVO_HOST=${BREVO_HOST}
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
