import type { Metadata } from 'next';
import '@radix-ui/themes/styles.css';
import { ClientProviders } from '@/app/ClientProviders';
import './globals.css';

export const metadata: Metadata = {
  title: 'Animal Shelter Connect',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
      <html lang="en">
        <body>
          <ClientProviders>{children}</ClientProviders>
        </body>
      </html>
  );
}
